server:
  port: 8889
spring:
  application:
    name: go8-mall
  thymeleaf:
    cache: false #方便开发
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url:  jdbc:mysql://localhost:3306/go8db?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 111
    driver-class-name:  com.mysql.cj.jdbc.Driver
  
  #es配置
  elasticsearch:
    cluster-nodes: 127.0.0.1:9300
logging:
  level:
    root: info
#custom properties
LOGIN_URL:  http://localhost:${server.port}/login.html